CREATE TABLE stp (
  id int AUTO_INCREMENT,
  compA enum('0', '1', '2') DEFAULT '2',
  compB enum('0', '1', '2') DEFAULT '2',
  compC enum('0', '1', '2') DEFAULT '2',
  compD enum('0', '1', '2') DEFAULT '2',
  bak1 enum('0', '1', '2') DEFAULT '2',
  bak2 enum('0', '1', '2') DEFAULT '2',
  bak3 enum('0', '1', '2') DEFAULT '2',
  bak4 enum('0', '1', '2') DEFAULT '2',
  bak5 enum('0', '1', '2') DEFAULT '2',
  bak6 enum('0', '1', '2') DEFAULT '2',
  bakKontrol7 enum('0', '1', '2') DEFAULT '2',
  submerPump1 enum('0', '1', '2') DEFAULT '2',
  submerPump2 enum('0', '1', '2') DEFAULT '2',
  chlorine enum('0', '1', '2') DEFAULT '2',
  boxPanel enum('0', '1', '2') DEFAULT '2',
  panel enum('0', '1', '2') DEFAULT '2',
  exhaustFan enum('0', '1', '2') DEFAULT '2',
  ruangan enum('0', '1', '2') DEFAULT '2',
  penerangan enum('0', '1', '2') DEFAULT '2',
  lantai enum('0', '1', '2') DEFAULT '2',
  atap enum('0', '1', '2') DEFAULT '2',
  dinding enum('0', '1', '2') DEFAULT '2',
  tangki enum('0', '1', '2') DEFAULT '2',
  checkDate datetime,
  checker varchar(30),
  note varchar(255),
  finding varchar(255),
  PRIMARY KEY (id)
);